# Generated by Django 4.0.4 on 2022-05-26 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='image_location',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
