# Generated by Django 4.0.4 on 2022-06-02 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gtapp', '0003_userweb'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Userweb',
        ),
    ]
