# Generated by Django 4.0.4 on 2022-06-09 20:09

import django.contrib.auth.password_validation
import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtapp', '0004_delete_userweb'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Example Carlo Mario', max_length=50)),
                ('last_name', models.CharField(help_text='Example Benedetti Postiga', max_length=50)),
                ('nickname', models.CharField(max_length=20, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator])),
                ('cell_phone', models.IntegerField(help_text='3001112233')),
                ('email_person', models.EmailField(max_length=254, unique=True)),
                ('date_create_user', models.DateTimeField(default='09-06-2022')),
                ('password_user', models.CharField(help_text='minimun eigth characters', max_length=32, validators=[django.contrib.auth.password_validation.validate_password])),
            ],
        ),
    ]
