# Generated by Django 4.0.4 on 2022-06-10 16:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gtapp', '0005_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='date_create_user',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
